# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
x = np.arange(10).reshape((2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
import numpy as np
y = np.ones((2,5)).astype("int64")
x = np.arange(10).reshape((2,5))                          
z = np.vstack((x,y))
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [7]:
z = np.hstack((x,y))
z

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]], dtype=int64)

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [9]:
print(x)
print(np.ravel(x))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [13]:
x = np.arange(15).reshape(3,5)
print(x)
y = np.ravel((x))
y

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [14]:
y.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [17]:
x = np.arange(25).reshape(5,5)
print(x)
y = np.sqrt(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
 [3.87298335 4.         4.12310563 4.24264069 4.35889894]
 [4.47213595 4.58257569 4.69041576 4.79583152 4.89897949]]


## Question:8

### Create 5x6 an array and find the mean?

In [20]:
x = np.arange(30).reshape(5,6)
print(x)
y = np.mean(x)
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [22]:
print(x)
z = np.std(x)
print(z)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
8.65544144839919


## Question:10

x### Find the median of the previous array in Q8?

In [24]:
c = np.median(x)
c

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [25]:
x.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [27]:
x = np.arange(16).reshape(4,4)
print(x)
y = np.diag(x)
print(y)
z = np.sum(y)
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]
30


## Question:13

### Find the determinant of the previous array in Q12?

In [30]:
z = np.linalg.det(x)
z

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [48]:
z = np.arange(10,120,10)
print(z)
y = np.percentile(z,5)
print(y)
c = np.percentile(z,95)
print(c)

[ 10  20  30  40  50  60  70  80  90 100 110]
15.0
105.0


## Question:15

### How to find if a given array has any null values?

In [61]:
x = np.array([0,4,8,19,30,0,40,98,0,44])
print(x)
y = np.nanpercentile(x,100)
print(y)
z = np.nanpercentile(x,80)
print(z)

[ 0  4  8 19 30  0 40 98  0 44]
98.0
40.8
